### PR TITLE
Support GHC 8.8 and 8.10

### PR DESCRIPTION
**Pull request by soareschen**
This change is [Reviewable](https://reviewable.io/reviews/scrive/consumers/4)

### CODE REVIEW

**Comment by arybczak** [comment]
https://hackage.haskell.org/package/hpqtypes-1.9.0.0

LGTM :+1:

**Comment by arybczak** [comment]
Actually, why did you relax `base` to `<5`? It doesn't buy you anything because hpqtypes has `base < 4.15`.

**Comment by soareschen** [comment]
We can relax `base` constraint for `hpqtypes` next time. GHC 8.10 is coming pretty soon. My current experience of patching countless Haskell packages just to update `base` tells me that it brings more trouble than it worth for over-restricting `base`. Type errors are sufficient to detect breaking changes to `base` are being used.

**Comment by arybczak** [comment]
> GHC 8.10 is coming pretty soon

GHC 8.10 is already released and its base is 4.14, so I'm not sure what you mean.

Though I agree on overly tight base bounds, I think `base < 5` is fine, it just needs to be set across the board.

**Comment by arybczak** [comment]
Right, I didn't notice that. Can you extend travis to test 8.10.1?

**Comment by arybczak** [comment]
Though for some reason I see it doesn't test PRs in this project.

**Comment by arybczak** [comment]
Tests fail and hpqtypes-extras dependency needs bounds fixed.

**Comment by soareschen** [comment]
Waiting for scrive/hpqtypes-extras#31.

**Pull request merged**
