### PR TITLE
Fix outdated CI

### PR DESCRIPTION
**Pull request by Raveline**
Result of running `haskell-ci regenerate` with the latest version of `haskell-ci`, since the checkout step doesn't work anymore.

### CODE REVIEW

**Review by jonathanjouty — COMMENTED** [review]
We should ideally update the GHC build matrix and the [tested with](https://github.com/scrive/consumers/blob/master/consumers.cabal#L21-L22) list too.

Looks good otherwise.

**Comment by Raveline** [comment]
You mean add the newer versions ? Can be done.

**Comment by Raveline** [comment]
I added 9.10.1, which is the latest available version. I think this should be enough for now.

**Comment by theophile-scrive** [comment]
We can probably reduce the CI setup to something less gnarly with https://github.com/kleidukos/get-tested

**Comment by Raveline** [comment]
That's an interesting setup, but one that we should reserve for another PR - right now my priority is to fix the build !

**Comment by theophile-scrive** [comment]
Yep, just food for thought.

**Pull request merged**
